version: "3"

services:
  scorecard:
    build:
      context: .
      args:
        USER_ID: ${USER_ID:-1001}
        GROUP_ID: ${GROUP_ID:-1001}
    command: bin/wait-for-postgres.sh python manage.py runserver 0.0.0.0:8001
    volumes:
      - ".:/app"
    environment:
      - DJANGO_DEBUG
      - DATABASE_URL=postgres://municipal_finance:municipal_finance@postgres/municipal_finance
      - DJANGO_SECRET_KEY=not-so-secret
      - SITE_ID=2
      - DATA_PORTAL_URL=http://portal:8002
      - ENVIRONMENT=development
      - SENTRY_DSN
      - SENTRY_PERF_SAMPLE_RATE
      - AWS_ACCESS_KEY_ID=minio-access-key
      - AWS_SECRET_ACCESS_KEY=minio-secret-key
      - AWS_STORAGE_BUCKET_NAME=municipal-money
      - AWS_S3_ENDPOINT_URL=http://minio:9000
      - AWS_S3_SECURE_URLS=True
      - AWS_S3_CUSTOM_DOMAIN
      - DJANGO_DEBUG_TOOLBAR
    ports:
      - '8001:8001'
    working_dir: /app
    depends_on:
      - postgres
      - portal
      - minio-client
      - minio
    stdin_open: true
    tty: true

  postgres:
    image: postgres:11.5
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=municipal_finance
      - POSTGRES_USER=municipal_finance
      - POSTGRES_PASSWORD=municipal_finance

  portal:
    build:
      context: .
      args:
        USER_ID: ${USER_ID:-1001}
        GROUP_ID: ${GROUP_ID:-1001}
      dockerfile: Dockerfile
    command: bin/wait-for-postgres.sh python manage.py runserver 0.0.0.0:8002
    # command: bin/wait-for-postgres.sh gunicorn --limit-request-line 7168 --worker-class gevent municipal_finance.wsgi:application -t 600 --log-file - -b 0.0.0.0:8002
    volumes:
      - ".:/app"
    environment:
      - DATABASE_URL=postgres://municipal_finance:municipal_finance@postgres/municipal_finance
      - DJANGO_SECRET_KEY=not-so-secret
      - ENVIRONMENT=development
      - SENTRY_DSN
      - SENTRY_PERF_SAMPLE_RATE
      - SITE_ID=3
      - PRELOAD_CUBES=true
      - DATA_PORTAL_URL=http://portal:8002
      - AWS_ACCESS_KEY_ID=minio-access-key
      - AWS_SECRET_ACCESS_KEY=minio-secret-key
      - AWS_STORAGE_BUCKET_NAME=municipal-money
      - AWS_S3_ENDPOINT_URL=http://minio:9000
      - AWS_S3_SECURE_URLS=True
      - AWS_S3_CUSTOM_DOMAIN
    working_dir: /app
    ports:
      - '8002:8002'
    depends_on:
      - postgres
      - minio

  worker:
    build:
      context: .
      args:
        USER_ID: ${USER_ID:-1001}
        GROUP_ID: ${GROUP_ID:-1001}
    command: bin/wait-for-postgres.sh python manage.py qcluster
    volumes:
      - ".:/app"
    environment:
      - DATABASE_URL=postgres://municipal_finance:municipal_finance@postgres/municipal_finance
      - DJANGO_SECRET_KEY=not-so-secret
      - ENVIRONMENT=development
      - SENTRY_DSN
      - SENTRY_PERF_SAMPLE_RATE
      - SITE_ID=2
      - PRELOAD_CUBES=true
      - DATA_PORTAL_URL=http://portal:8002
      - AWS_ACCESS_KEY_ID=minio-access-key
      - AWS_SECRET_ACCESS_KEY=minio-secret-key
      - AWS_STORAGE_BUCKET_NAME=municipal-money
      - AWS_S3_ENDPOINT_URL=http://minio:9000
      - AWS_S3_SECURE_URLS=True
      - AWS_S3_CUSTOM_DOMAIN
    working_dir: /app
    depends_on:
      - postgres
      - minio
    restart: on-failure

  test:
    build:
      context: .
      args:
        USER_ID: ${USER_ID:-1001}
        GROUP_ID: ${GROUP_ID:-1001}
      dockerfile: Dockerfile-test
    command: bin/wait-for-postgres.sh python manage.py test municipal_finance scorecard infrastructure
    volumes:
      - ".:/app"
    environment:
      - DJANGO_DEBUG
      - DATABASE_URL=postgres://municipal_finance:municipal_finance@postgres/municipal_finance
      - DJANGO_SECRET_KEY=not-so-secret
      - SITE_ID=2
      - DATA_PORTAL_URL=http://portal:8002
      - ENVIRONMENT=development
      - SENTRY_DSN
      - SENTRY_PERF_SAMPLE_RATE
      - AWS_ACCESS_KEY_ID=minio-access-key
      - AWS_SECRET_ACCESS_KEY=minio-secret-key
      - AWS_STORAGE_BUCKET_NAME=municipal-money
      - AWS_S3_ENDPOINT_URL=http://minio:9000
      - AWS_S3_SECURE_URLS=True
      - AWS_S3_CUSTOM_DOMAIN
      - DJANGO_DEBUG_TOOLBAR
      - NO_INDEX
    working_dir: /app
    depends_on:
      - postgres
      - minio
    stdin_open: true
    tty: true

  minio:
    image: "minio/minio:RELEASE.2019-10-12T01-39-57Z"
    volumes:
      - minio_data:/data
    ports:
      - "9000:9000"
    environment:
      - MINIO_ACCESS_KEY=minio-access-key
      - MINIO_SECRET_KEY=minio-secret-key
      - MINIO_DOMAIN=minio
    command: minio --compat server data

  minio-client:
    image: "minio/mc:RELEASE.2019-12-17T23-26-28Z"
    depends_on:
      - minio
    environment:
      - MINIO_ACCESS_KEY=minio-access-key
      - MINIO_SECRET_KEY=minio-secret-key
      - MINIO_DOMAIN=minio
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc config host add --quiet --api s3v4 local http://minio:9000 minio-access-key minio-secret-key;
      /usr/bin/mc mb  local/municipal-money;
      /usr/bin/mc policy set public local/municipal-money;
      "

volumes:
  minio_data: {}
  postgres_data: {}
  munimoney_search: {}
