# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-25 11:05
from __future__ import unicode_literals

from django.db import migrations
from django.contrib.sites.models import Site


def create_sites(apps, schema_editor):
    Site(domain='municipalmoney.org.za', name='Scorecard').save()
    Site(domain='data.municipalmoney.org.za', name='API').save()


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(create_sites)
    ]
