# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-17 13:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('municipal_finance', '0002_auto_20161117_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='scorecardgeography',
            name='development_category',
            field=models.TextField(null=True),
        ),
    ]
