# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-12-06 15:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('municipal_finance', '0002_auto_20161117_1531'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemarcationChanges',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('old_code', models.TextField()),
                ('new_code', models.TextField()),
                ('old_code_transition', models.TextField()),
                ('new_code_transition', models.TextField()),
            ],
        ),
    ]
