# Generated by Django 2.2.28 on 2024-07-24 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('municipal_finance', '0004_add_data_summary_and_item_schema'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cflowitemsv1',
            name='composition',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cflowitemsv2',
            name='composition',
            field=models.TextField(blank=True, null=True),
        ),
    ]
