# Generated by Django 2.2.28 on 2024-07-24 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('municipal_finance', '0004_add_data_summary_and_item_schema'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cflowitemsv1',
            name='composition',
        ),
        migrations.RemoveField(
            model_name='cflowitemsv2',
            name='composition',
        ),
    ]
