# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-03-01 09:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('municipal_finance', '0005_auto_20170228_1627'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='agedcreditorfacts',
            unique_together=set([('amount_type_code', 'demarcation_code', 'financial_period', 'financial_year', 'item_code', 'period_length'), ('demarcation_code', 'period_code', 'item_code')]),
        ),
    ]
