# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-03-01 10:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('municipal_finance', '0007_auto_20170301_1216'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='capitalfacts',
            unique_together=set([('amount_type_code', 'demarcation_code', 'financial_period', 'financial_year', 'function_code', 'item_code', 'period_length'), ('demarcation_code', 'period_code', 'function_code', 'item_code')]),
        ),
    ]
