# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-03-01 10:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('municipal_finance', '0008_auto_20170301_1223'),
    ]

    operations = [
        migrations.RunSQL("""
        update cflow_facts set
        financial_year = cast(left(period_code, 4) as int),
        amount_type_code = case when period_code ~ '^\d{4}(IBY1|IBY2|ADJB|ORGB|AUDA|PAUD)(M\d{2})?$'
                                    then substr(period_code, 5, 4)
                                when period_code ~ '^\d{4}M\d{2}$'
                                    then 'ACT'
                             end,
        period_length = case when period_code ~ '^\d{4}(ADJB|ORGB)?M\d{2}$'
                                 then 'month'
                             when period_code ~ '^\d{4}(IBY1|IBY2|ADJB|ORGB|AUDA|PAUD)$'
                                 then 'year'
       end,
        financial_period = case when period_code ~ '^\d{4}(ADJB|ORGB)?M\d{2}$'
                                    then cast(right(period_code, 2) as int)
                                when period_code ~ '^\d{4}(IBY1|IBY2|ADJB|ORGB|AUDA|PAUD)$'
                                    then cast(left(period_code, 4) as int)
        end;
        """),
        migrations.AlterUniqueTogether(
            name='cflowfacts',
            unique_together=set([('amount_type_code', 'demarcation_code', 'financial_period', 'financial_year', 'item_code', 'period_length'), ('demarcation_code', 'period_code', 'item_code')]),
        ),
        migrations.RunSQL("""
        update conditional_grants_facts set
        financial_year = cast(left(period_code, 4) as int),
        amount_type_code = case when period_code ~ '^\d{4}(ADJB|ORGB|SCHD|TRFR)(M\d{2})?$'
                                    then substr(period_code, 5, 4)
                                when period_code ~ '^\d{4}M\d{2}$'
                                    then 'ACT'
        end,
        period_length = case when period_code ~ '^\d{4}M\d{2}$'
                                 then 'month'
                             when period_code ~ '^\d{4}(ADJB|ORGB|SCHD|TRFR)$'
                                 then 'year'
       end,
        financial_period = case when period_code ~ '^\d{4}M\d{2}$'
                                    then cast(right(period_code, 2) as int)
                                when period_code ~ '^\d{4}(ADJB|ORGB|SCHD|TRFR)$'
                                    then cast(left(period_code, 4) as int)
        end;
        """),
        migrations.AlterUniqueTogether(
            name='conditionalgrantsfacts',
            unique_together=set([('demarcation_code', 'period_code', 'grant_code'), ('amount_type_code', 'demarcation_code', 'financial_period', 'financial_year', 'grant_code', 'period_length')]),
        ),
    ]
