# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-09-29 15:11
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('municipal_finance', '0010_auto_20170301_1256'),
    ]

    operations = [
        migrations.CreateModel(
            name='MunicipalityProfile',
            fields=[
                ('demarcation_code', models.CharField(
                    max_length=10, primary_key=True, serialize=False)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
            options={
                'db_table': 'municipality_profile',
            },
        ),
        migrations.CreateModel(
            name='MunicipalityProfilesRebuild',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'municipality_profiles_rebuild',
            },
        ),
        migrations.CreateModel(
            name='MunicipalityStaffContactsUpload',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(upload_to='uploads/contacts/')),
                ('user', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'municipality_staff_contacts_uploads',
            },
        ),
        # migrations.AlterField(
        #     model_name='municipalitystaffcontacts',
        #     name='demarcation_code',
        #     field=models.TextField(primary_key=True, serialize=False),
        # ),
        # migrations.RemoveField(
        #     model_name='municipalitystaffcontacts',
        #     name='id',
        # ),
        # migrations.AlterUniqueTogether(
        #     name='municipalitystaffcontacts',
        #     unique_together=set([('demarcation_code', 'role')]),
        # ),
    ]
