# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-09-19 13:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('municipal_finance', '0010_auto_20170301_1256'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactsUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('file', models.FileField(upload_to='uploads/contacts/')),
            ],
            options={
                'db_table': 'contacts_uploads',
            },
        ),
    ]
