# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-10-27 09:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('municipal_finance', '0012_mediangroup_ratingcountgroup'),
    ]

    operations = [
        migrations.CreateModel(
            name='CflowFactsMSCOA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('demarcation_code', models.TextField()),
                ('period_code', models.TextField()),
                ('amount', models.BigIntegerField(null=True)),
                ('amount_type_code', models.TextField()),
                ('financial_year', models.IntegerField()),
                ('period_length', models.TextField()),
                ('financial_period', models.IntegerField()),
            ],
            options={
                'db_table': 'cflow_facts_mscoa',
            },
        ),
        migrations.CreateModel(
            name='CflowItemsMSCOA',
            fields=[
                ('code', models.TextField(primary_key=True, serialize=False)),
                ('label', models.TextField()),
                ('position_in_return_form', models.IntegerField(null=True)),
                ('return_form_structure', models.TextField(null=True)),
                ('composition', models.TextField(null=True)),
            ],
            options={
                'db_table': 'cflow_items_mscoa',
            },
        ),
        migrations.RenameModel(
            old_name='CflowFacts',
            new_name='CflowFactsLegacy',
        ),
        migrations.RenameModel(
            old_name='CflowItems',
            new_name='CflowItemsLegacy',
        ),
        migrations.AlterUniqueTogether(
            name='cflowfactslegacy',
            unique_together=set([]),
        ),
        migrations.AddField(
            model_name='cflowfactsmscoa',
            name='item_code',
            field=models.ForeignKey(db_column='item_code', on_delete=django.db.models.deletion.DO_NOTHING, to='municipal_finance.CflowItemsMSCOA'),
        ),
    ]
