# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-12-03 07:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('municipal_finance', '0020_v1_initial_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='MunicipalityProfilesCompilation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('last_audit_year', models.IntegerField()),
                ('last_opinion_year', models.IntegerField()),
                ('last_uifw_year', models.IntegerField()),
                ('last_audit_quarter', models.CharField(max_length=6)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'municipality_profiles_compilation',
            },
        ),
        migrations.RemoveField(
            model_name='municipalityprofilesrebuild',
            name='user',
        ),
        migrations.AlterField(
            model_name='municipalitystaffcontactsupload',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='MunicipalityProfilesRebuild',
        ),
    ]
