# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-11-25 09:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import municipal_finance.models.small_auto_field


class Migration(migrations.Migration):

    dependencies = [
        ('municipal_finance', '0021_auto_20201203_0951'),
    ]

    operations = [
        migrations.CreateModel(
            name='CapitalFactsV2',
            fields=[
                ('demarcation_code', models.TextField()),
                ('period_code', models.TextField()),
                ('financial_year', models.IntegerField()),
                ('period_length', models.TextField()),
                ('financial_period', models.IntegerField()),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('amount', models.BigIntegerField(null=True)),
                ('amount_type', models.ForeignKey(
                    on_delete=django.db.models.deletion.DO_NOTHING, to='municipal_finance.AmountTypeV2')),
            ],
            options={
                'db_table': 'capital_facts_v2',
            },
        ),
        migrations.CreateModel(
            name='CapitalItemsV2',
            fields=[
                ('label', models.TextField()),
                ('id', municipal_finance.models.small_auto_field.SmallAutoField(
                    primary_key=True, serialize=False)),
                ('code', models.TextField(unique=True)),
            ],
            options={
                'db_table': 'capital_items_v2',
            },
        ),
        migrations.CreateModel(
            name='CapitalTypeV2',
            fields=[
                ('id', municipal_finance.models.small_auto_field.SmallAutoField(
                    primary_key=True, serialize=False)),
                ('code', models.TextField(unique=True)),
                ('label', models.TextField(unique=True)),
            ],
            options={
                'db_table': 'capital_type_v2',
            },
        ),
        migrations.RenameModel(
            old_name='CapitalFacts',
            new_name='CapitalFactsV1',
        ),
        migrations.RenameModel(
            old_name='CapitalItems',
            new_name='CapitalItemsV1',
        ),
        migrations.AlterUniqueTogether(
            name='capitalfactsv1',
            unique_together=set([('demarcation_code', 'function_code', 'item_code', 'period_code'), ('demarcation_code',
                                                                                                     'function_code', 'item_code', 'amount_type_code', 'financial_period', 'financial_year', 'period_length')]),
        ),
        migrations.AddField(
            model_name='capitalfactsv2',
            name='capital_type',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to='municipal_finance.CapitalTypeV2'),
        ),
        migrations.AddField(
            model_name='capitalfactsv2',
            name='function',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING,
                                    to='municipal_finance.GovernmentFunctionsV2'),
        ),
        migrations.AddField(
            model_name='capitalfactsv2',
            name='item',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to='municipal_finance.CapitalItemsV2'),
        ),
        migrations.AlterUniqueTogether(
            name='capitalfactsv2',
            unique_together=set([('demarcation_code', 'function', 'item', 'capital_type', 'amount_type', 'financial_period',
                                  'financial_year', 'period_length'), ('demarcation_code', 'function', 'item', 'capital_type', 'period_code')]),
        ),
    ]
