# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-12-06 11:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import municipal_finance.models.small_auto_field


class Migration(migrations.Migration):

    dependencies = [
        ('municipal_finance', '0028_repairs_maintenance_items_initial_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgedDebtorFactsV2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('demarcation_code', models.TextField()),
                ('period_code', models.TextField()),
                ('customer_group_code', models.TextField()),
                ('bad_amount', models.BigIntegerField(null=True)),
                ('badi_amount', models.BigIntegerField(null=True)),
                ('g1_amount', models.BigIntegerField(null=True)),
                ('l1_amount', models.BigIntegerField(null=True)),
                ('l120_amount', models.BigIntegerField(null=True)),
                ('l150_amount', models.BigIntegerField(null=True)),
                ('l180_amount', models.BigIntegerField(null=True)),
                ('l30_amount', models.BigIntegerField(null=True)),
                ('l60_amount', models.BigIntegerField(null=True)),
                ('l90_amount', models.BigIntegerField(null=True)),
                ('total_amount', models.BigIntegerField(null=True)),
                ('financial_year', models.IntegerField()),
                ('period_length', models.TextField()),
                ('financial_period', models.IntegerField()),
                ('amount_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='municipal_finance.AmountTypeV2')),
            ],
            options={
                'db_table': 'aged_debtor_facts_v2',
            },
        ),
        migrations.CreateModel(
            name='AgedDebtorItemsV2',
            fields=[
                ('label', models.TextField()),
                ('position_in_return_form', models.IntegerField(null=True)),
                ('return_form_structure', models.TextField(null=True)),
                ('composition', models.TextField(null=True)),
                ('id', municipal_finance.models.small_auto_field.SmallAutoField(primary_key=True, serialize=False)),
                ('code', models.TextField(unique=True)),
            ],
            options={
                'db_table': 'aged_debtor_items_v2',
            },
        ),
        migrations.RenameModel(
            old_name='AgedDebtorFacts',
            new_name='AgedDebtorFactsV1',
        ),
        migrations.RenameModel(
            old_name='AgedDebtorItems',
            new_name='AgedDebtorItemsV1',
        ),
        migrations.AddField(
            model_name='ageddebtorfactsv2',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='municipal_finance.AgedDebtorItemsV2'),
        ),
        migrations.AlterUniqueTogether(
            name='ageddebtorfactsv2',
            unique_together=set([('amount_type', 'customer_group_code', 'demarcation_code', 'financial_period', 'financial_year', 'item', 'period_length'), ('demarcation_code', 'period_code', 'customer_group_code', 'item')]),
        ),
    ]
