# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-12-11 14:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('municipal_finance', '0032_aged_creditor_items_initial_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashFlowV2Update',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('deleted', models.BigIntegerField(null=True)),
                ('inserted', models.BigIntegerField(null=True)),
                ('file', models.FileField(max_length=255, upload_to='updates/cash_flow_v2/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cash_flow_v2_update',
            },
        ),
        migrations.CreateModel(
            name='IncomeExpenditureV2Update',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('deleted', models.BigIntegerField(null=True)),
                ('inserted', models.BigIntegerField(null=True)),
                ('file', models.FileField(max_length=255, upload_to='updates/income_expenditure_v2/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'income_expenditure_v2_update',
            },
        ),
        migrations.CreateModel(
            name='MunicipalStaffContactsUpdate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('deleted', models.BigIntegerField(null=True)),
                ('inserted', models.BigIntegerField(null=True)),
                ('file', models.FileField(max_length=255, upload_to='updates/municipal_staff_contacts/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'municipal_staff_contacts_update',
            },
        ),
        migrations.CreateModel(
            name='RepairsMaintenanceV2Update',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('deleted', models.BigIntegerField(null=True)),
                ('inserted', models.BigIntegerField(null=True)),
                ('file', models.FileField(max_length=255, upload_to='updates/repairs_maintenance_v2/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'repairs_maintenance_v2_update',
            },
        ),
        migrations.RenameModel(
            old_name='MunicipalityStaffContacts',
            new_name='MunicipalStaffContacts',
        ),
        migrations.RemoveField(
            model_name='municipalitystaffcontactsupload',
            name='user',
        ),
        migrations.AlterModelTable(
            name='municipalstaffcontacts',
            table='municipal_staff_contacts',
        ),
        migrations.DeleteModel(
            name='MunicipalityStaffContactsUpload',
        ),
    ]
