# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-12-14 14:07
from __future__ import unicode_literals

from django.db import migrations, models
import municipal_finance.models.updates


class Migration(migrations.Migration):

    dependencies = [
        ('municipal_finance', '0033_auto_20201211_1648'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BsheetFactsV2',
            new_name='FinancialPositionFactsV2',
        ),
        migrations.RenameModel(
            old_name='BsheetItemsV2',
            new_name='FinancialPositionItemsV2',
        ),
        migrations.AlterField(
            model_name='cashflowv2update',
            name='file',
            field=models.FileField(
                max_length=255, upload_to=municipal_finance.models.updates.UpdateFilePath()),
        ),
        migrations.AlterField(
            model_name='incomeexpenditurev2update',
            name='file',
            field=models.FileField(
                max_length=255, upload_to=municipal_finance.models.updates.UpdateFilePath()),
        ),
        migrations.AlterField(
            model_name='municipalstaffcontactsupdate',
            name='file',
            field=models.FileField(
                max_length=255, upload_to=municipal_finance.models.updates.UpdateFilePath()),
        ),
        migrations.AlterField(
            model_name='repairsmaintenancev2update',
            name='file',
            field=models.FileField(
                max_length=255, upload_to=municipal_finance.models.updates.UpdateFilePath()),
        ),
        migrations.AlterModelTable(
            name='financialpositionfactsv2',
            table='financial_position_facts_v2',
        ),
        migrations.AlterModelTable(
            name='financialpositionitemsv2',
            table='financial_position_items_v2',
        ),
    ]
