# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-12-16 16:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import municipal_finance.models.updates


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('municipal_finance', '0035_financial_position_items_v2_initial_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgedCreditorFactsV2Update',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('deleted', models.BigIntegerField(null=True)),
                ('inserted', models.BigIntegerField(null=True)),
                ('file', models.FileField(max_length=255, upload_to=municipal_finance.models.updates.UpdateFilePath())),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'aged_creditors_facts_v2_update',
            },
        ),
        migrations.CreateModel(
            name='AgedDebtorFactsV2Update',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('deleted', models.BigIntegerField(null=True)),
                ('inserted', models.BigIntegerField(null=True)),
                ('file', models.FileField(max_length=255, upload_to=municipal_finance.models.updates.UpdateFilePath())),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'aged_debtors_facts_v2_update',
            },
        ),
        migrations.CreateModel(
            name='AuditOpinionFactsUpdate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('deleted', models.BigIntegerField(null=True)),
                ('inserted', models.BigIntegerField(null=True)),
                ('file', models.FileField(max_length=255, upload_to=municipal_finance.models.updates.UpdateFilePath())),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'audit_opinion_facts_update',
            },
        ),
        migrations.CreateModel(
            name='CapitalFactsV2Update',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('deleted', models.BigIntegerField(null=True)),
                ('inserted', models.BigIntegerField(null=True)),
                ('file', models.FileField(max_length=255, upload_to=municipal_finance.models.updates.UpdateFilePath())),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'capital_facts_v2_update',
            },
        ),
        migrations.CreateModel(
            name='FinancialPositionFactsV2Update',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('deleted', models.BigIntegerField(null=True)),
                ('inserted', models.BigIntegerField(null=True)),
                ('file', models.FileField(max_length=255, upload_to=municipal_finance.models.updates.UpdateFilePath())),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'financial_position_facts_v2_update',
            },
        ),
        migrations.CreateModel(
            name='GrantFactsV2Update',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('deleted', models.BigIntegerField(null=True)),
                ('inserted', models.BigIntegerField(null=True)),
                ('file', models.FileField(max_length=255, upload_to=municipal_finance.models.updates.UpdateFilePath())),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'grant_facts_v2_update',
            },
        ),
        migrations.CreateModel(
            name='UIFWExpenseFactsUpdate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('deleted', models.BigIntegerField(null=True)),
                ('inserted', models.BigIntegerField(null=True)),
                ('file', models.FileField(max_length=255, upload_to=municipal_finance.models.updates.UpdateFilePath())),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'uifw_expense_facts_update',
            },
        ),
        migrations.RenameModel(
            old_name='UifwexpFacts',
            new_name='UIFWExpenseFacts',
        ),
        migrations.AlterModelOptions(
            name='demarcationchanges',
            options={'verbose_name_plural': 'Demarcation Changes'},
        ),
        migrations.AddField(
            model_name='capitalitemsv2',
            name='composition',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='capitalitemsv2',
            name='position_in_return_form',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='capitalitemsv2',
            name='return_form_structure',
            field=models.TextField(null=True),
        ),
    ]
