# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-02-12 11:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('municipal_finance', '0038_auto_20210208_1014'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MedianGroup',
        ),
        migrations.DeleteModel(
            name='MunicipalityProfile',
        ),
        migrations.RemoveField(
            model_name='municipalityprofilescompilation',
            name='user',
        ),
        migrations.DeleteModel(
            name='RatingCountGroup',
        ),
        migrations.DeleteModel(
            name='MunicipalityProfilesCompilation',
        ),
    ]
