# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-02-22 03:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('municipal_finance', '0039_auto_20210212_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demarcationchanges',
            name='new_code_transition',
            field=models.CharField(choices=[('disestablished', 'Disestablished'), ('established', 'Established'), ('continue', 'Continue')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='demarcationchanges',
            name='old_code_transition',
            field=models.CharField(choices=[('disestablished', 'Disestablished'), ('established', 'Established'), ('continue', 'Continue')], db_index=True, max_length=20),
        ),
    ]
