# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-09-20 15:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('municipal_finance', '0042_set_indexes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agedcreditorfactsv1',
            name='item_code',
        ),
    ]
