# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-09-20 15:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('municipal_finance', '0042_set_indexes'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='agedcreditorfactsv1',
            unique_together=set([('demarcation_code', 'period_code', 'item'), ('amount_type_code', 'demarcation_code', 'financial_period', 'financial_year', 'period_length', 'item')]),
        ),
        migrations.RemoveField(
            model_name='agedcreditorfactsv1',
            name='item_code',
        ),
    ]
