# Generated by Django 2.2.28 on 2023-07-06 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('municipal_finance', '0044_portal_data_summary'),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkDownload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_url', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Bulk Downloads',
                'db_table': 'bulk_doownload',
            },
        ),
    ]
