# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-10-26 16:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('municipal_finance', '0044_auto_20221026_1858'),
    ]

    operations = [
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Data Summaries',
                'db_table': 'data_summaries',
            },
        ),
    ]
