# Generated by Django 2.2.28 on 2023-06-08 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('municipal_finance', '0044_portal_data_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='agedcreditorfactsv2update',
            name='task_id',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='ageddebtorfactsv2update',
            name='task_id',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='auditopinionfactsupdate',
            name='task_id',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='capitalfactsv2update',
            name='task_id',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='cashflowv2update',
            name='task_id',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='financialpositionfactsv2update',
            name='task_id',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='grantfactsv2update',
            name='task_id',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='incomeexpenditurev2update',
            name='task_id',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='municipalstaffcontactsupdate',
            name='task_id',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='repairsmaintenancev2update',
            name='task_id',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='uifwexpensefactsupdate',
            name='task_id',
            field=models.TextField(null=True),
        ),
    ]
