# Generated by Django 2.2.28 on 2023-11-06 14:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import municipal_finance.models.updates


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('municipal_finance', '0045_auto_20230614_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialpositionitemsv2',
            name='code',
            field=models.TextField(),
        ),
        migrations.CreateModel(
            name='ItemCodeSchema',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('task_id', models.TextField(editable=False, null=True)),
                ('version', models.CharField(max_length=10, unique=True)),
                ('file', models.FileField(max_length=255, upload_to=municipal_finance.models.updates.UpdateFilePath())),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Item Code Schema',
                'db_table': 'item_code_schema',
            },
        ),
        migrations.AddField(
            model_name='financialpositionitemsv2',
            name='version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='municipal_finance.ItemCodeSchema'),
        ),
        migrations.AlterUniqueTogether(
            name='financialpositionitemsv2',
            unique_together={('code', 'version')},
        ),
    ]
