# Generated by Django 2.2.28 on 2023-07-07 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('municipal_finance', '0045_auto_20230614_1503'),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkDownload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Bulk Downloads',
                'db_table': 'bulk_download',
            },
        ),
    ]
