# Generated by Django 2.2.28 on 2023-11-13 22:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import municipal_finance.models.updates


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('municipal_finance', '0045_auto_20230614_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capitalitemsv2',
            name='code',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='cflowitemsv2',
            name='code',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='financialpositionitemsv2',
            name='code',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='incexpitemsv2',
            name='code',
            field=models.TextField(),
        ),
        migrations.AddField(
            model_name='capitalitemsv2',
            name='version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='municipal_finance.ItemCodeSchema'),
        ),
        migrations.AddField(
            model_name='cflowitemsv2',
            name='version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='municipal_finance.ItemCodeSchema'),
        ),
        migrations.AddField(
            model_name='financialpositionitemsv2',
            name='version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='municipal_finance.ItemCodeSchema'),
        ),
        migrations.AddField(
            model_name='incexpitemsv2',
            name='version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='municipal_finance.ItemCodeSchema'),
        ),
        migrations.AlterUniqueTogether(
            name='capitalitemsv2',
            unique_together={('code', 'version')},
        ),
        migrations.AlterUniqueTogether(
            name='financialpositionitemsv2',
            unique_together={('code', 'version')},
        ),
        migrations.AlterUniqueTogether(
            name='incexpitemsv2',
            unique_together={('code', 'version')},
        ),
    ]
