# Generated by Django 2.2.28 on 2023-11-29 11:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

from ..resources import (
    CapitalTypeV2Resource,
    CapitalItemsV1Resource,
    CashflowItemsV2Resource,
    IncexpItemsV2Resource,
    FinancialPositionItemsV2Resource,
    CapitalItemsV2Resource
)

from . import run_data_import


def add_new_schema(apps, schema_editor):
    schema = apps.get_model('municipal_finance', 'ItemCodeSchema')
    version = schema(version=0)
    version.save()


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('municipal_finance', '0046_auto_20231114_0015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capitalitemsv2',
            name='code',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='cflowitemsv2',
            name='code',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='financialpositionitemsv2',
            name='code',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='incexpitemsv2',
            name='code',
            field=models.TextField(),
        ),
        migrations.AddField(
            model_name='capitalitemsv2',
            name='version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='municipal_finance.ItemCodeSchema'),
        ),
        migrations.AddField(
            model_name='cflowitemsv2',
            name='version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='municipal_finance.ItemCodeSchema'),
        ),
        migrations.AddField(
            model_name='financialpositionitemsv2',
            name='version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='municipal_finance.ItemCodeSchema'),
        ),
        migrations.AddField(
            model_name='incexpitemsv2',
            name='version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='municipal_finance.ItemCodeSchema'),
        ),
        migrations.AlterUniqueTogether(
            name='capitalitemsv2',
            unique_together={('code', 'version')},
        ),
        migrations.AlterUniqueTogether(
            name='financialpositionitemsv2',
            unique_together={('code', 'version')},
        ),
        migrations.AlterUniqueTogether(
            name='incexpitemsv2',
            unique_together={('code', 'version')},
        ),
        migrations.RunPython(add_new_schema),
        run_data_import(CapitalItemsV1Resource, 'capital_items_v1.csv'),
        run_data_import(CapitalTypeV2Resource, 'capital_type_v2.csv'),
        run_data_import(CashflowItemsV2Resource, 'cash_flow_items_v2.csv'),
        run_data_import(
            IncexpItemsV2Resource, 'income_expenditure_items_v2.csv',
        ),
        run_data_import(
            FinancialPositionItemsV2Resource,
            'financial_position_items_v2.csv',
        ),
        run_data_import(CapitalItemsV2Resource, 'capital_items_v2.csv'),
        migrations.AlterField(
            model_name='conditionalgranttypesv1',
            name='code',
            field=models.TextField(primary_key=True, serialize=False),
        ),
    ]
