# Generated by Django 2.2.28 on 2023-11-29 10:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('municipal_finance', '0046_auto_20231114_0015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conditionalgranttypesv1',
            name='code',
            field=models.TextField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='itemcodeschema',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
