# Generated by Django 2.2.28 on 2023-11-29 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('municipal_finance', '0046_auto_20231114_0015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conditionalgranttypesv1',
            name='code',
            field=models.TextField(primary_key=True, serialize=False),
        ),
    ]
