V1_INCOME_TOTAL_CODE = "1900"
V1_INCOME_LOCAL_CODES = [
    "0200", "0300", "0400", "0700", "0800", "1000",
    "1100", "1300", "1400", "1500", "1700", "1800"
]
V1_INCOME_TRANSFERS_CODES = ["1600", "1610"]
# Excludes total code for consistency with v2
V1_INCOME_ITEMS = [
    *V1_INCOME_LOCAL_CODES,
    *V1_INCOME_TRANSFERS_CODES,
]
V2_INCOME_LOCAL_CODES = [
    "0200", "0300", "0400", "0500", "0600", "0800", "0900", "1000", "1100",
    "1200", "1300", "1400", "1600", "1700",
]
V2_INCOME_TRANSFERS_CODES = ["1500"]
V2_INCOME_ITEMS = [
    *V2_INCOME_LOCAL_CODES,
    *V2_INCOME_TRANSFERS_CODES,
]

V1_SPENDING_TOTAL_CODE = "4600"
V1_SPENDING_CODES = [
    "3000", "3100", "3200", "3300", "3400", "3600", "3900", "4000", "4100",
    "4200", "4300", "3500", "3700", "4110", "4400", "4500", "4550",
]
V2_SPENDING_CODES = [
    "2000", "2100", "2200", "2300", "2400", "2500", "2600", "2700", "2800",
    "2900", "3000",
]

# function label: custom category
V2_FUNCTIONAL_BREAKDOWN = {
    "Abattoirs": "Other",
    "Administrative and Corporate Support": "Corporate Services",
    "Aged Care": "Community & Social Services",
    "Agricultural": "Community & Social Services",
    "Air Transport": "Other",
    "Ambulance": "Health",
    "Animal Care and Diseases": "Community & Social Services",
    "Asset Management": "Corporate Services",
    "Beaches and Jetties": "Sport And Recreation",
    "Billboards": "Planning and Development",
    "Biodiversity and Landscape": "Environmental Protection",
    "Casinos, Racing, Gambling, Wagering": "Sport And Recreation",
    "Cemeteries, Funeral Parlours and Crematoriums": "Community & Social Services",
    "Central City Improvement District": "Planning and Development",
    "Chemical Safety": "Health",
    "Child Care Facilities": "Community & Social Services",
    "Civil Defence": "Public Safety",
    "Cleansing": "Public Safety",
    "Coastal Protection": "Environmental Protection",
    "Community Halls and Facilities": "Community & Social Services",
    "Community Parks (including Nurseries)": "Sport And Recreation",
    "Consumer Protection": "Community & Social Services",
    "Control of Public Nuisances": "Public Safety",
    "Corporate Wide Strategic Planning (IDPs, LEDs)": "Planning and Development",
    "Cultural Matters": "Community & Social Services",
    "Development Facilitation": "Planning and Development",
    "Disaster Management": "Community & Social Services",
    "Economic Development/Planning": "Planning and Development",
    "Education": "Community & Social Services",
    "Electricity": "Electricity ",
    "Fencing and Fences": "Public Safety",
    "Finance": "Corporate Services",
    "Fire Fighting and Protection": "Public Safety",
    "Fleet Management": "Corporate Services",
    "Food Control": "Health",
    "Forestry": "Other",
    "Governance Function": "Budget & Treasury Office ",
    "Health Services": "Health",
    "Health Surveillance and Prevention of Communicable Diseases including immunizations": "Health",
    "Housing": "Housing",
    "Human Resources": "Corporate Services",
    "Indigenous and Customary Law": "Community & Social Services",
    "Indigenous Forests": "Environmental Protection",
    "Industrial Promotion": "Community & Social Services",
    "Informal Settlements": "Housing",
    "Information Technology": "Corporate Services",
    "Laboratory Services": "Health",
    "Language Policy": "Community & Social Services",
    "Legal Services": "Corporate Services",
    "Libraries and Archives": "Community & Social Services",
    "Licensing and Control of Animals": "Public Safety",
    "Licensing and Regulation": "Planning and Development",
    "Literacy Programmes": "Community & Social Services",
    "Marketing, Customer Relations, Publicity and Media Co-ordination": "Corporate Services",
    "Markets": "Other",
    "Mayor and Council": "Executive & Council",
    "Media Services": "Community & Social Services",
    "Municipal Manager, Town Secretary and Chief Executive": "Executive & Council",
    "Museums and Art Galleries": "Community & Social Services",
    "Nature Conservation": "Environmental Protection",
    "Nonelectric Energy": "Other",
    "Police Forces, Traffic and Street Parking Control": "Public Safety",
    "Pollution Control": "Environmental Protection",
    "Population Development": "Community & Social Services",
    "Pounds": "Public Safety",
    "Project Management Unit": "Planning and Development",
    "Property Services": "Corporate Services",
    "Provincial Cultural Matters": "Community & Social Services",
    "Provincial Planning": "Planning and Development",
    "Public Toilets": "Waste Water Management",
    "Public Transport": "Road Transport",
    "Recreational Facilities": "Sport And Recreation",
    "Recycling": "Waste Management",
    "Regional Planning and Development": "Planning and Development",
    "Risk Management": "Corporate Services",
    "Road and Traffic Regulation": "Road Transport",
    "Roads": "Road Transport",
    "Security Services": "Corporate Services",
    "Sewerage": "Waste Water Management",
    "Soil Conservation": "Environmental Protection",
    "Solid Waste Disposal (Landfill Sites)": "Waste Management",
    "Solid Waste Removal": "Waste Management",
    "Sports Grounds and Stadiums": "Sport And Recreation",
    "Storm Water Management": "Waste Water Management",
    "Street Cleaning": "Waste Management",
    "Street Lighting and Signal Systems": "Electricity ",
    "Supply Chain Management": "Corporate Services",
    "Support to Local Municipalities": "Planning and Development",
    "Taxi Ranks": "Road Transport",
    "Theatres": "Community & Social Services",
    "Tourism": "Other",
    "Town Planning, Building Regulations and Enforcement, and City Engineer": "Planning and Development",
    "Valuation Service": "Corporate Services",
    "Vector Control": "Health",
    "Waste Water Treatment": "Waste Water Management",
    "Water Distribution": "Water",
    "Water Storage": "Water",
    "Water Treatment": "Water",
    "Zoo's": "Community & Social Services",
}
