# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-10-31 06:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scorecard', '0003_geography_population'),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetPhase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Expenditure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('budget_phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='infrastructure.BudgetPhase')),
            ],
        ),
        migrations.CreateModel(
            name='FinancialYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budget_year', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('function', models.CharField(blank=True, max_length=150)),
                ('project_description', models.CharField(blank=True, max_length=255)),
                ('project_number', models.CharField(blank=True, max_length=30)),
                ('project_type', models.CharField(blank=True, max_length=20)),
                ('mtsf_service_outcome', models.CharField(blank=True, max_length=50)),
                ('iudf', models.CharField(blank=True, max_length=50)),
                ('own_strategic_objective', models.CharField(blank=True, max_length=50)),
                ('asset_class', models.CharField(blank=True, max_length=50)),
                ('asset_subclass', models.CharField(blank=True, max_length=50)),
                ('ward_location', models.CharField(blank=True, max_length=50)),
                ('longitude', models.FloatField(null=True)),
                ('latitude', models.FloatField(null=True)),
                ('financial_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='infrastructure.FinancialYear')),
                ('geography', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='geographies', to='scorecard.Geography')),
            ],
        ),
        migrations.AddField(
            model_name='expenditure',
            name='financial_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='infrastructure.FinancialYear'),
        ),
        migrations.AddField(
            model_name='expenditure',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenditures', to='infrastructure.Project'),
        ),
    ]
