# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-10-31 09:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='financial_year',
        ),
    ]
