# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-10-31 09:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0002_remove_project_financial_year'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='own_strategic_objective',
            new_name='own_strategic_objectives',
        ),
    ]
