# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-10-31 15:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0003_auto_20191031_0959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='asset_class',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='asset_subclass',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='iudf',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='mtsf_service_outcome',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='own_strategic_objectives',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='ward_location',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
