# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-10-31 16:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0004_auto_20191031_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetphase',
            name='code',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
