# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-11-27 10:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0005_auto_20191031_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenditure',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenditure', to='infrastructure.Project'),
        ),
        migrations.AlterField(
            model_name='project',
            name='own_strategic_objectives',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
