# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-01-09 18:48
from __future__ import unicode_literals

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0007_auto_20191127_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='content_search',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddIndex(
            model_name='project',
            index=django.contrib.postgres.indexes.GinIndex(fields=['content_search'], name='infrastruct_content_2af341_gin'),
        ),
    ]
