# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-06-01 10:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0010_auto_20200527_1439'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuarterlySpendFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='quarterly/')),
                ('financial_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='infrastructure.FinancialYear')),
            ],
        ),
    ]
