# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-06-02 10:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scorecard", "0003_geography_population"),
        ("infrastructure", "0011_quarterlyspendfile"),
    ]

    operations = [
        migrations.AddField(
            model_name="quarterlyspendfile",
            name="status",
            field=models.IntegerField(default=3),
        ),
    ]
