# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-09-15 14:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0016_auto_20210907_0131'),
    ]

    operations = [
        migrations.RenameField(
            model_name='annualspendfile',
            old_name='financial_year',
            new_name='implementation_financial_year',
        ),
    ]
