# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-09-28 11:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0016_auto_20210907_0131'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='latest_implementation_year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='infrastructure.FinancialYear'),
        ),
        migrations.AlterField(
            model_name='annualspendfile',
            name='financial_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='infrastructure.FinancialYear', verbose_name='Implementation financial year'),
        ),
    ]
