# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-11-17 15:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0019_auto_20211006_1456'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financialyear',
            name='active',
        ),
    ]
