# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-03-03 13:32
from __future__ import unicode_literals

from django.db import migrations

def add_financial_year(apps, schema_editor):
    FinancialYear = apps.get_model('household', 'FinancialYear')
    FinancialYear.objects.create(budget_year="2015/2016")
    FinancialYear.objects.create(budget_year="2016/2017")
    FinancialYear.objects.create(budget_year="2017/2018")
    FinancialYear.objects.create(budget_year='2018/2019')
    FinancialYear.objects.create(budget_year='2019/2020')
    FinancialYear.objects.create(budget_year='2020/2021')

def add_budget_phase(apps, schema_editor):
    BudgetPhase = apps.get_model('household', 'BudgetPhase')
    BudgetPhase.objects.create(name='Audited Outcome')
    BudgetPhase.objects.create(name='Original Budget')
    BudgetPhase.objects.create(name='Adjusted Budget')
    BudgetPhase.objects.create(name='Budget Year')

def add_class(apps, schema_editor):
    HouseholdClass = apps.get_model('household', 'HouseholdClass')
    HouseholdClass.objects.create(name="Middle Income Range")
    HouseholdClass.objects.create(name="Affordable Range")
    HouseholdClass.objects.create(name='Indigent HH receiving FBS')

def add_service(apps, schema_editor):
    HouseholdService = apps.get_model('household', 'HouseholdService')
    HouseholdService.objects.create(name='Property Rates')
    HouseholdService.objects.create(name='Electricity: Basic levy')
    HouseholdService.objects.create(name='Electricity: Consumption')
    HouseholdService.objects.create(name='Water: Basic levy')
    HouseholdService.objects.create(name='Water: Consumption')
    HouseholdService.objects.create(name='Sanitation')
    HouseholdService.objects.create(name='Refuse removal')
    HouseholdService.objects.create(name='Other')

class Migration(migrations.Migration):

    dependencies = [
        ('household', '0001_initial'),
    ]
    operations = [
        migrations.RunPython(add_financial_year),
        migrations.RunPython(add_budget_phase),
        migrations.RunPython(add_class),
        migrations.RunPython(add_service)
    ]
