# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-03-09 12:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('household', '0003_auto_20200309_1436'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='householdbill',
            name='service_vat',
        ),
        migrations.AddField(
            model_name='householdincrease',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
