# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-03-09 12:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('household', '0004_auto_20200309_1448'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HouseholdIncrease',
            new_name='HouseholdBillIncrease',
        ),
        migrations.RenameModel(
            old_name='HouseholdBill',
            new_name='HouseholdServiceBill',
        ),
    ]
