# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-03-10 11:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('household', '0005_auto_20200309_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasetfile',
            name='file_type',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
