# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-03-10 13:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('household', '0006_datasetfile_file_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasetversion',
            name='version',
            field=models.IntegerField(unique=True),
        ),
    ]
