# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-03-10 13:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('household', '0007_auto_20200310_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='householdbillincrease',
            name='percent',
            field=models.FloatField(null=True),
        ),
    ]
