# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-03-10 14:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('household', '0008_auto_20200310_1550'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HouseholdBillIncrease',
            new_name='HouseholdBillTotal',
        ),
        migrations.RenameModel(
            old_name='HouseholdServiceBill',
            new_name='HouseholdServiceTotal',
        ),
    ]
