# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-03-23 11:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('household', '0010_financialyear_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='householdbilltotal',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='householdservicetotal',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
    ]
