# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-04-08 09:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('household', '0013_auto_20200323_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialyear',
            name='year_range',
            field=models.IntegerField(default=0),
        ),
    ]
