# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-04-08 09:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('household', '0014_financialyear_year_range'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialyear',
            name='year_range',
            field=models.CharField(choices=[(1, 'Oldest'), (2, 'Newest')], default='0', max_length=2),
        ),
    ]
