# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-04-09 09:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('household', '0015_auto_20200408_1154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financialyear',
            name='year_range',
        ),
    ]
