# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-04-09 09:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('household', '0016_remove_financialyear_year_range'),
    ]

    operations = [
        migrations.AddField(
            model_name='householdclass',
            name='max_value',
            field=models.IntegerField(default=10000),
        ),
        migrations.AddField(
            model_name='householdclass',
            name='min_value',
            field=models.IntegerField(default=0),
        ),
    ]
