# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-04-09 10:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('household', '0017_auto_20200409_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='householdclass',
            name='max_value',
            field=models.DecimalField(decimal_places=2, default=10000, max_digits=10),
        ),
        migrations.AlterField(
            model_name='householdclass',
            name='min_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
