# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-09-08 12:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('household', '0018_auto_20200409_1246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datasetfile',
            name='version',
        ),
        migrations.RemoveField(
            model_name='householdbilltotal',
            name='version',
        ),
        migrations.RemoveField(
            model_name='householdservicetotal',
            name='version',
        ),
        migrations.DeleteModel(
            name='DataSetVersion',
        ),
    ]
