# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-04-23 10:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='FinancialYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budget_year', models.CharField(max_length=10)),
                ('active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Indicator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=255)),
                ('tier', models.CharField(max_length=20)),
                ('reporting', models.CharField(max_length=50)),
                ('measurement', models.CharField(max_length=100)),
                ('alignment', models.CharField(max_length=100)),
                ('formula', models.CharField(max_length=100)),
                ('fequency', models.CharField(max_length=100)),
                ('definition', models.CharField(max_length=255)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicators', to='metro.Category')),
            ],
        ),
        migrations.CreateModel(
            name='IndicatorElements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('definition', models.CharField(max_length=255)),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='metro.Indicator')),
            ],
        ),
    ]
