# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-04-23 10:34
from __future__ import unicode_literals

from django.db import migrations
from django.conf import settings
import csv
import os


def add_financial_years(apps, schema_editor):
    FinancialYear = apps.get_model("metro", "FinancialYear")
    FinancialYear.objects.create(budget_year="2021/22")
    FinancialYear.objects.create(budget_year="2020/21")
    FinancialYear.objects.create(budget_year="2019/20")
    FinancialYear.objects.create(budget_year="2018/19")
    FinancialYear.objects.create(budget_year="2017/28")


def add_category(apps, schema_editor):
    Category = apps.get_model("metro", "Category")
    category_path = os.path.join(
        settings.BASE_DIR, "metro", "data", "category_details.csv"
    )
    with open(category_path, "r") as csv_file:
        reader = csv.DictReader(csv_file)
        for row in reader:
            Category.objects.create(name=row["Category"], code=row["Category Code"])


class Migration(migrations.Migration):

    dependencies = [
        ("metro", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(add_financial_years),
        migrations.RunPython(add_category),
    ]
