# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-04-23 13:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metro', '0002_auto_20200423_1234'),
    ]

    operations = [
        migrations.RenameField(
            model_name='indicator',
            old_name='fequency',
            new_name='frequency',
        ),
        migrations.AlterField(
            model_name='indicator',
            name='definition',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='formula',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='indicatorelements',
            name='definition',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='indicatorelements',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
