# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-04-23 12:30
from __future__ import unicode_literals

from django.db import migrations
from django.conf import settings
import csv
import os


def add_elements(apps, schema_editor):
    Indicator = apps.get_model("metro", "Indicator")
    Elements = apps.get_model("metro", "IndicatorElements")
    indicator_path = os.path.join(
        settings.BASE_DIR, "metro", "data", "data_elements.csv"
    )
    with open(indicator_path, "r") as csv_file:
        reader = csv.DictReader(csv_file)
        for row in reader:
            indicator = Indicator.objects.get(code=row["Indicator Code"])
            Elements.objects.create(
                indicator=indicator,
                code=row["Data Element Code"],
                name=row["Name"],
                definition=row["Definition"],
            )


class Migration(migrations.Migration):

    dependencies = [
        ("metro", "0004_auto_20200423_1515"),
    ]

    operations = [migrations.RunPython(add_elements)]
