# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-05-06 09:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('metro', '0006_auto_20200423_1535'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndicatorQuarterResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quarter_one', models.CharField(max_length=10)),
                ('quarter_two', models.CharField(max_length=10)),
                ('quarter_three', models.CharField(max_length=10)),
                ('quarter_four', models.CharField(max_length=10)),
                ('final_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metro.FinancialYear')),
            ],
        ),
        migrations.AddField(
            model_name='indicator',
            name='target',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='indicatorquarterresult',
            name='indicator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metro.Indicator'),
        ),
    ]
