# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-05-06 10:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scorecard', '0003_geography_population'),
        ('metro', '0007_auto_20200506_1110'),
    ]

    operations = [
        migrations.RenameField(
            model_name='indicatorquarterresult',
            old_name='final_year',
            new_name='financial_year',
        ),
        migrations.AddField(
            model_name='indicatorquarterresult',
            name='geography',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scorecard.Geography'),
        ),
    ]
