# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-05-07 12:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metro', '0009_auto_20200507_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicatorquarterresult',
            name='quarter_four',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='indicatorquarterresult',
            name='quarter_one',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='indicatorquarterresult',
            name='quarter_three',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='indicatorquarterresult',
            name='quarter_two',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
