# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-05-08 11:19
from __future__ import unicode_literals

from django.db import migrations
from django.utils.text import slugify


def category_slug(apps, schema_editor):
    Category = apps.get_model("metro", "Category")
    for cat in Category.objects.all():
        cat.slug = slugify(cat.name)
        cat.save()


class Migration(migrations.Migration):

    dependencies = [
        ("metro", "0011_auto_20200508_1319"),
    ]

    operations = [migrations.RunPython(category_slug)]
