# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-05-13 07:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('metro', '0012_auto_20200508_1319'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='financialyear',
            managers=[
                ('financial_year', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='indicator',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
