# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-05-13 07:41
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("metro", "0013_auto_20200513_0929"),
    ]

    operations = [
        migrations.RemoveField(model_name="indicator", name="slug",),
        migrations.AddField(
            model_name="indicator",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
    ]
