# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-05-13 07:41
from __future__ import unicode_literals

from django.db import migrations
import uuid


def indicator_uuid(apps, schema_editor):
    Indicator = apps.get_model("metro", "Indicator")
    for indicator in Indicator.objects.all():
        indicator.uuid = uuid.uuid4()
        indicator.save()


class Migration(migrations.Migration):

    dependencies = [
        ("metro", "0014_auto_20200513_0941"),
    ]

    operations = [migrations.RunPython(indicator_uuid)]
