# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-05-14 14:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scorecard', '0003_geography_population'),
        ('metro', '0016_auto_20200513_0949'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicator',
            name='geography',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scorecard.Geography'),
        ),
    ]
