# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-05-14 14:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metro', '0018_auto_20200514_1630'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indicator',
            name='target',
        ),
        migrations.AddField(
            model_name='indicatorquarterresult',
            name='target',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
