# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-05-14 15:04
from __future__ import unicode_literals

from django.db import migrations
import csv
import os
from django.conf import settings


def add_indicators(apps, schema_editor):
    Indicator = apps.get_model("metro", "Indicator")
    Category = apps.get_model("metro", "Category")

    for indicator in Indicator.objects.all():
        indicator.delete()

    indicator_path = os.path.join(
        settings.BASE_DIR, "metro", "data", "indicator_details.csv"
    )
    with open(indicator_path, "r") as csv_file:
        reader = csv.DictReader(csv_file)
        for row in reader:
            category = Category.objects.get(code=row["Category Code"])
            Indicator.objects.create(
                category=category,
                code=row["Indicator Code"],
                name=row["Indicator"],
                tier=row["Tier"],
                reporting=row["Reporting Responsibility"],
                measurement=row["Measurement"],
                alignment=row["Alignment"],
                formula=row["Indicator Formula"],
                frequency=row["Frequency of Reporting"],
                definition=row["Definition"],
            )


class Migration(migrations.Migration):

    dependencies = [
        ("metro", "0020_auto_20200514_1655"),
    ]

    operations = [migrations.RunPython(add_indicators)]
