# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-05-20 09:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scorecard', '0003_geography_population'),
        ('metro', '0021_auto_20200514_1704'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indicator',
            name='geography',
        ),
        migrations.AlterUniqueTogether(
            name='indicator',
            unique_together=set([('code', 'name')]),
        ),
        migrations.AlterUniqueTogether(
            name='indicatorelements',
            unique_together=set([('code', 'name')]),
        ),
        migrations.AlterUniqueTogether(
            name='indicatorquarterresult',
            unique_together=set([('indicator', 'financial_year', 'geography')]),
        ),
    ]
