# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-06-08 09:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metro', '0022_auto_20200520_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicator',
            name='goal',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
