# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-06-09 09:56
from __future__ import unicode_literals

from django.db import migrations


def indicator_goal(apps, schema_editor):
    """
    populate certain indicators with target goals
    """
    Indicator = apps.get_model("metro", "Indicator")

    indicators = {
        "EE1.11": "Higher is better",
        "EE3.11": "Higher is better",
        "EE3.21": "Higher is better",
        "GG1.21": "Lower is better",
        "GG4.11": "Lower is better",
        "GG6.11": "Higher is better",
        "GG6.12": "Higher is better",
        "WS2.11": "Higher is better",
        "WS1.11": "Higher is better",
    }
    for key, value in indicators.items():
        ind = Indicator.objects.get(code=key)
        ind.goal = value
        ind.save()


class Migration(migrations.Migration):

    dependencies = [
        ("metro", "0023_indicator_goal"),
    ]

    operations = [migrations.RunPython(indicator_goal)]
