# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-06-09 14:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metro', '0024_auto_20200609_1156'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialQuarter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quarter', models.CharField(max_length=5, unique=True)),
                ('active', models.BooleanField(default=False)),
            ],
        ),
    ]
