# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-06-09 14:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metro', '0025_financialquarter'),
    ]

    operations = [
    ]
