# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-06-09 15:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metro', '0026_auto_20200609_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialyear',
            name='quarter',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
