# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-06-10 10:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scorecard', '0003_geography_population'),
        ('metro', '0027_financialyear_quarter'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpdateFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='quarterly/')),
            ],
        ),
        migrations.DeleteModel(
            name='FinancialQuarter',
        ),
        migrations.AlterField(
            model_name='financialyear',
            name='quarter',
            field=models.CharField(help_text='Current quarter of the financial year', max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='updatefile',
            name='financial_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metro.FinancialYear'),
        ),
        migrations.AddField(
            model_name='updatefile',
            name='geography',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scorecard.Geography'),
        ),
    ]
