# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-06-10 11:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metro', '0028_auto_20200610_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='updatefile',
            name='quarter',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
