# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-06-10 12:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metro', '0029_updatefile_quarter'),
    ]

    operations = [
        migrations.AddField(
            model_name='updatefile',
            name='status',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
