# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-06-18 15:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metro', '0030_updatefile_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='updatefile',
            name='status',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
