# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-24 15:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scorecard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='geography',
            name='miif_category',
            field=models.TextField(null=True),
        ),
    ]
