# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-25 14:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scorecard', '0002_geography_development_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='geography',
            old_name='development_category',
            new_name='miif_category',
        ),
    ]
