# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-06-29 18:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scorecard', '0002_geography_development_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='geography',
            name='year',
        ),
        migrations.AddField(
            model_name='geography',
            name='population',
            field=models.IntegerField(null=True),
        ),
        migrations.RunSQL("""update scorecard_geography s
                             set population = pop.population
                             from population_2011 pop
                             where pop.geo_level = s.geo_level and pop.geo_code = s.geo_code""",
                          migrations.RunSQL.noop)
    ]
