# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-12-16 14:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scorecard', '0003_geography_population'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='geography',
            options={'verbose_name_plural': 'Geographies'},
        ),
    ]
