# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-02-10 06:40
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scorecard', '0004_auto_20201216_1653'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedianGroup',
            fields=[
                ('group_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='MunicipalityProfile',
            fields=[
                ('demarcation_code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
            options={
                'db_table': 'municipality_profile',
            },
        ),
        migrations.CreateModel(
            name='MunicipalityProfilesCompilation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('last_audit_year', models.IntegerField()),
                ('last_opinion_year', models.IntegerField()),
                ('last_uifw_year', models.IntegerField()),
                ('last_audit_quarter', models.CharField(max_length=6)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Municipality Profile Compilation',
                'db_table': 'municipality_profiles_compilation',
            },
        ),
        migrations.CreateModel(
            name='RatingCountGroup',
            fields=[
                ('group_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
    ]
