# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-07-18 16:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scorecard', '0005_mediangroup_municipalityprofile_municipalityprofilescompilation_ratingcountgroup'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeographyUpdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Geography Update',
                'db_table': 'scorecard_geography_update',
            },
        ),
    ]
