# Generated by Django 2.2.28 on 2023-06-15 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scorecard', '0007_auto_20221129_1829'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='municipalityprofilescompilation',
            options={'verbose_name': 'Municipality Profile Compilation', 'verbose_name_plural': 'Municipality Profile Compilations'},
        ),
    ]
