CREATE INDEX repmaint_labeled_amount_type_code_idx ON repmaint_labeled (amount_type_code);
CREATE INDEX repmaint_labeled_amount_type_label_idx ON repmaint_labeled (amount_type_label);
CREATE INDEX repmaint_labeled_dimension_amount_type_idx ON repmaint_labeled (amount_type_code, amount_type_label);
CREATE INDEX repmaint_labeled_demarcation_code_idx ON repmaint_labeled (demarcation_code);
CREATE INDEX repmaint_labeled_demarcation_label_idx ON repmaint_labeled (demarcation_label);
CREATE INDEX repmaint_labeled_dimension_demarcation_idx ON repmaint_labeled (demarcation_code, demarcation_label);
CREATE INDEX repmaint_labeled_period_length_idx ON repmaint_labeled (period_length);
CREATE INDEX repmaint_labeled_position_in_return_form_idx ON repmaint_labeled (position_in_return_form);
CREATE INDEX repmaint_labeled_item_code_idx ON repmaint_labeled (item_code);
CREATE INDEX repmaint_labeled_return_form_structure_idx ON repmaint_labeled (return_form_structure);
CREATE INDEX repmaint_labeled_composition_idx ON repmaint_labeled (composition);
CREATE INDEX repmaint_labeled_item_label_idx ON repmaint_labeled (item_label);
CREATE INDEX repmaint_labeled_dimension_item_idx ON repmaint_labeled (item_code, composition, item_label, position_in_return_form, return_form_structure);
CREATE INDEX repmaint_labeled_item_ordered_idx ON repmaint_labeled (position_in_return_form, item_code, composition, item_label, return_form_structure);
CREATE INDEX repmaint_labeled_financial_period_idx ON repmaint_labeled (financial_period);
CREATE INDEX repmaint_labeled_financial_year_idx ON repmaint_labeled (financial_year);
CREATE INDEX aged_creditor_labeled_amount_type_code_idx ON aged_creditor_labeled (amount_type_code);
CREATE INDEX aged_creditor_labeled_amount_type_label_idx ON aged_creditor_labeled (amount_type_label);
CREATE INDEX aged_creditor_labeled_dimension_amount_type_idx ON aged_creditor_labeled (amount_type_code, amount_type_label);
CREATE INDEX aged_creditor_labeled_demarcation_code_idx ON aged_creditor_labeled (demarcation_code);
CREATE INDEX aged_creditor_labeled_demarcation_label_idx ON aged_creditor_labeled (demarcation_label);
CREATE INDEX aged_creditor_labeled_dimension_demarcation_idx ON aged_creditor_labeled (demarcation_code, demarcation_label);
CREATE INDEX aged_creditor_labeled_period_length_idx ON aged_creditor_labeled (period_length);
CREATE INDEX aged_creditor_labeled_position_in_return_form_idx ON aged_creditor_labeled (position_in_return_form);
CREATE INDEX aged_creditor_labeled_item_code_idx ON aged_creditor_labeled (item_code);
CREATE INDEX aged_creditor_labeled_return_form_structure_idx ON aged_creditor_labeled (return_form_structure);
CREATE INDEX aged_creditor_labeled_composition_idx ON aged_creditor_labeled (composition);
CREATE INDEX aged_creditor_labeled_item_label_idx ON aged_creditor_labeled (item_label);
CREATE INDEX aged_creditor_labeled_dimension_item_idx ON aged_creditor_labeled (item_code, composition, item_label, position_in_return_form, return_form_structure);
CREATE INDEX aged_creditor_labeled_item_ordered_idx ON aged_creditor_labeled (position_in_return_form, item_code, composition, item_label, return_form_structure);
CREATE INDEX aged_creditor_labeled_financial_period_idx ON aged_creditor_labeled (financial_period);
CREATE INDEX aged_creditor_labeled_financial_year_idx ON aged_creditor_labeled (financial_year);
CREATE INDEX incexp_labeled_function_code_idx ON incexp_labeled (function_code);
CREATE INDEX incexp_labeled_function_label_idx ON incexp_labeled (function_label);
CREATE INDEX incexp_labeled_dimension_function_idx ON incexp_labeled (function_code, function_label);
CREATE INDEX incexp_labeled_amount_type_code_idx ON incexp_labeled (amount_type_code);
CREATE INDEX incexp_labeled_amount_type_label_idx ON incexp_labeled (amount_type_label);
CREATE INDEX incexp_labeled_dimension_amount_type_idx ON incexp_labeled (amount_type_code, amount_type_label);
CREATE INDEX incexp_labeled_demarcation_code_idx ON incexp_labeled (demarcation_code);
CREATE INDEX incexp_labeled_demarcation_label_idx ON incexp_labeled (demarcation_label);
CREATE INDEX incexp_labeled_dimension_demarcation_idx ON incexp_labeled (demarcation_code, demarcation_label);
CREATE INDEX incexp_labeled_period_length_idx ON incexp_labeled (period_length);
CREATE INDEX incexp_labeled_position_in_return_form_idx ON incexp_labeled (position_in_return_form);
CREATE INDEX incexp_labeled_item_code_idx ON incexp_labeled (item_code);
CREATE INDEX incexp_labeled_return_form_structure_idx ON incexp_labeled (return_form_structure);
CREATE INDEX incexp_labeled_composition_idx ON incexp_labeled (composition);
CREATE INDEX incexp_labeled_item_label_idx ON incexp_labeled (item_label);
CREATE INDEX incexp_labeled_dimension_item_idx ON incexp_labeled (item_code, composition, item_label, position_in_return_form, return_form_structure);
CREATE INDEX incexp_labeled_item_ordered_idx ON incexp_labeled (position_in_return_form, item_code, composition, item_label, return_form_structure);
CREATE INDEX incexp_labeled_financial_period_idx ON incexp_labeled (financial_period);
CREATE INDEX incexp_labeled_financial_year_idx ON incexp_labeled (financial_year);
CREATE INDEX grants_labeled_amount_type_code_idx ON grants_labeled (amount_type_code);
CREATE INDEX grants_labeled_amount_type_label_idx ON grants_labeled (amount_type_label);
CREATE INDEX grants_labeled_dimension_amount_type_idx ON grants_labeled (amount_type_code, amount_type_label);
CREATE INDEX grants_labeled_demarcation_code_idx ON grants_labeled (demarcation_code);
CREATE INDEX grants_labeled_demarcation_label_idx ON grants_labeled (demarcation_label);
CREATE INDEX grants_labeled_dimension_demarcation_idx ON grants_labeled (demarcation_code, demarcation_label);
CREATE INDEX grants_labeled_grant_code_idx ON grants_labeled (grant_code);
CREATE INDEX grants_labeled_grant_name_idx ON grants_labeled (grant_name);
CREATE INDEX grants_labeled_dimension_grant_idx ON grants_labeled (grant_code, grant_name);
CREATE INDEX grants_labeled_period_length_idx ON grants_labeled (period_length);
CREATE INDEX grants_labeled_financial_period_idx ON grants_labeled (financial_period);
CREATE INDEX grants_labeled_financial_year_idx ON grants_labeled (financial_year);
CREATE INDEX bsheet_labeled_amount_type_code_idx ON bsheet_labeled (amount_type_code);
CREATE INDEX bsheet_labeled_amount_type_label_idx ON bsheet_labeled (amount_type_label);
CREATE INDEX bsheet_labeled_dimension_amount_type_idx ON bsheet_labeled (amount_type_code, amount_type_label);
CREATE INDEX bsheet_labeled_demarcation_code_idx ON bsheet_labeled (demarcation_code);
CREATE INDEX bsheet_labeled_demarcation_label_idx ON bsheet_labeled (demarcation_label);
CREATE INDEX bsheet_labeled_dimension_demarcation_idx ON bsheet_labeled (demarcation_code, demarcation_label);
CREATE INDEX bsheet_labeled_period_length_idx ON bsheet_labeled (period_length);
CREATE INDEX bsheet_labeled_position_in_return_form_idx ON bsheet_labeled (position_in_return_form);
CREATE INDEX bsheet_labeled_item_code_idx ON bsheet_labeled (item_code);
CREATE INDEX bsheet_labeled_return_form_structure_idx ON bsheet_labeled (return_form_structure);
CREATE INDEX bsheet_labeled_composition_idx ON bsheet_labeled (composition);
CREATE INDEX bsheet_labeled_item_label_idx ON bsheet_labeled (item_label);
CREATE INDEX bsheet_labeled_dimension_item_idx ON bsheet_labeled (item_code, composition, item_label, position_in_return_form, return_form_structure);
CREATE INDEX bsheet_labeled_item_ordered_idx ON bsheet_labeled (position_in_return_form, item_code, composition, item_label, return_form_structure);
CREATE INDEX bsheet_labeled_financial_period_idx ON bsheet_labeled (financial_period);
CREATE INDEX bsheet_labeled_financial_year_idx ON bsheet_labeled (financial_year);
CREATE INDEX cflow_labeled_amount_type_code_idx ON cflow_labeled (amount_type_code);
CREATE INDEX cflow_labeled_amount_type_label_idx ON cflow_labeled (amount_type_label);
CREATE INDEX cflow_labeled_dimension_amount_type_idx ON cflow_labeled (amount_type_code, amount_type_label);
CREATE INDEX cflow_labeled_demarcation_code_idx ON cflow_labeled (demarcation_code);
CREATE INDEX cflow_labeled_demarcation_label_idx ON cflow_labeled (demarcation_label);
CREATE INDEX cflow_labeled_dimension_demarcation_idx ON cflow_labeled (demarcation_code, demarcation_label);
CREATE INDEX cflow_labeled_period_length_idx ON cflow_labeled (period_length);
CREATE INDEX cflow_labeled_position_in_return_form_idx ON cflow_labeled (position_in_return_form);
CREATE INDEX cflow_labeled_item_code_idx ON cflow_labeled (item_code);
CREATE INDEX cflow_labeled_return_form_structure_idx ON cflow_labeled (return_form_structure);
CREATE INDEX cflow_labeled_composition_idx ON cflow_labeled (composition);
CREATE INDEX cflow_labeled_item_label_idx ON cflow_labeled (item_label);
CREATE INDEX cflow_labeled_dimension_item_idx ON cflow_labeled (item_code, composition, item_label, position_in_return_form, return_form_structure);
CREATE INDEX cflow_labeled_item_ordered_idx ON cflow_labeled (position_in_return_form, item_code, composition, item_label, return_form_structure);
CREATE INDEX cflow_labeled_financial_period_idx ON cflow_labeled (financial_period);
CREATE INDEX cflow_labeled_financial_year_idx ON cflow_labeled (financial_year);
CREATE INDEX municipality_contacts_demarcation_code_idx ON municipality_contacts (demarcation_code);
CREATE INDEX municipality_contacts_role_idx ON municipality_contacts (role);
CREATE INDEX municipality_contacts_office_number_idx ON municipality_contacts (office_number);
CREATE INDEX municipality_contacts_title_idx ON municipality_contacts (title);
CREATE INDEX municipality_contacts_email_address_idx ON municipality_contacts (email_address);
CREATE INDEX municipality_contacts_fax_number_idx ON municipality_contacts (fax_number);
CREATE INDEX municipality_contacts_name_idx ON municipality_contacts (name);
CREATE INDEX municipality_contacts_dimension_contact_details_idx ON municipality_contacts (email_address, fax_number, name, office_number, title);
CREATE INDEX aged_debtor_labeled_amount_type_code_idx ON aged_debtor_labeled (amount_type_code);
CREATE INDEX aged_debtor_labeled_amount_type_label_idx ON aged_debtor_labeled (amount_type_label);
CREATE INDEX aged_debtor_labeled_dimension_amount_type_idx ON aged_debtor_labeled (amount_type_code, amount_type_label);
CREATE INDEX aged_debtor_labeled_demarcation_code_idx ON aged_debtor_labeled (demarcation_code);
CREATE INDEX aged_debtor_labeled_demarcation_label_idx ON aged_debtor_labeled (demarcation_label);
CREATE INDEX aged_debtor_labeled_dimension_demarcation_idx ON aged_debtor_labeled (demarcation_code, demarcation_label);
CREATE INDEX aged_debtor_labeled_period_length_idx ON aged_debtor_labeled (period_length);
CREATE INDEX aged_debtor_labeled_customer_group_code_idx ON aged_debtor_labeled (customer_group_code);
CREATE INDEX aged_debtor_labeled_position_in_return_form_idx ON aged_debtor_labeled (position_in_return_form);
CREATE INDEX aged_debtor_labeled_item_code_idx ON aged_debtor_labeled (item_code);
CREATE INDEX aged_debtor_labeled_return_form_structure_idx ON aged_debtor_labeled (return_form_structure);
CREATE INDEX aged_debtor_labeled_composition_idx ON aged_debtor_labeled (composition);
CREATE INDEX aged_debtor_labeled_item_label_idx ON aged_debtor_labeled (item_label);
CREATE INDEX aged_debtor_labeled_dimension_item_idx ON aged_debtor_labeled (item_code, composition, item_label, position_in_return_form, return_form_structure);
CREATE INDEX aged_debtor_labeled_item_ordered_idx ON aged_debtor_labeled (position_in_return_form, item_code, composition, item_label, return_form_structure);
CREATE INDEX aged_debtor_labeled_financial_period_idx ON aged_debtor_labeled (financial_period);
CREATE INDEX aged_debtor_labeled_financial_year_idx ON aged_debtor_labeled (financial_year);
CREATE INDEX scorecard_geography_category_idx ON scorecard_geography (category);
CREATE INDEX scorecard_geography_province_code_idx ON scorecard_geography (province_code);
CREATE INDEX scorecard_geography_name_idx ON scorecard_geography (name);
CREATE INDEX scorecard_geography_url_idx ON scorecard_geography (url);
CREATE INDEX scorecard_geography_street_address_4_idx ON scorecard_geography (street_address_4);
CREATE INDEX scorecard_geography_street_address_1_idx ON scorecard_geography (street_address_1);
CREATE INDEX scorecard_geography_fax_number_idx ON scorecard_geography (fax_number);
CREATE INDEX scorecard_geography_street_address_3_idx ON scorecard_geography (street_address_3);
CREATE INDEX scorecard_geography_street_address_2_idx ON scorecard_geography (street_address_2);
CREATE INDEX scorecard_geography_long_name_idx ON scorecard_geography (long_name);
CREATE INDEX scorecard_geography_postal_address_1_idx ON scorecard_geography (postal_address_1);
CREATE INDEX scorecard_geography_postal_address_3_idx ON scorecard_geography (postal_address_3);
CREATE INDEX scorecard_geography_postal_address_2_idx ON scorecard_geography (postal_address_2);
CREATE INDEX scorecard_geography_parent_code_idx ON scorecard_geography (parent_code);
CREATE INDEX scorecard_geography_phone_number_idx ON scorecard_geography (phone_number);
CREATE INDEX scorecard_geography_province_name_idx ON scorecard_geography (province_name);
CREATE INDEX scorecard_geography_geo_code_idx ON scorecard_geography (geo_code);
CREATE INDEX scorecard_geography_dimension_municipality_idx ON scorecard_geography (category, geo_code, fax_number, long_name, name, parent_code, phone_number, postal_address_1, postal_address_2, postal_address_3, province_code, province_name, street_address_1, street_address_2, street_address_3, street_address_4, url);
CREATE INDEX audit_opinions_opinion_code_idx ON audit_opinions (opinion_code);
CREATE INDEX audit_opinions_opinion_label_idx ON audit_opinions (opinion_label);
CREATE INDEX audit_opinions_dimension_opinion_idx ON audit_opinions (opinion_code, opinion_label);
CREATE INDEX audit_opinions_demarcation_code_idx ON audit_opinions (demarcation_code);
CREATE INDEX audit_opinions_financial_year_idx ON audit_opinions (financial_year);
CREATE INDEX capital_labeled_function_code_idx ON capital_labeled (function_code);
CREATE INDEX capital_labeled_function_label_idx ON capital_labeled (function_label);
CREATE INDEX capital_labeled_dimension_function_idx ON capital_labeled (function_code, function_label);
CREATE INDEX capital_labeled_amount_type_code_idx ON capital_labeled (amount_type_code);
CREATE INDEX capital_labeled_amount_type_label_idx ON capital_labeled (amount_type_label);
CREATE INDEX capital_labeled_dimension_amount_type_idx ON capital_labeled (amount_type_code, amount_type_label);
CREATE INDEX capital_labeled_demarcation_code_idx ON capital_labeled (demarcation_code);
CREATE INDEX capital_labeled_demarcation_label_idx ON capital_labeled (demarcation_label);
CREATE INDEX capital_labeled_dimension_demarcation_idx ON capital_labeled (demarcation_code, demarcation_label);
CREATE INDEX capital_labeled_period_length_idx ON capital_labeled (period_length);
CREATE INDEX capital_labeled_position_in_return_form_idx ON capital_labeled (position_in_return_form);
CREATE INDEX capital_labeled_item_code_idx ON capital_labeled (item_code);
CREATE INDEX capital_labeled_return_form_structure_idx ON capital_labeled (return_form_structure);
CREATE INDEX capital_labeled_composition_idx ON capital_labeled (composition);
CREATE INDEX capital_labeled_item_label_idx ON capital_labeled (item_label);
CREATE INDEX capital_labeled_dimension_item_idx ON capital_labeled (item_code, composition, item_label, position_in_return_form, return_form_structure);
CREATE INDEX capital_labeled_item_ordered_idx ON capital_labeled (position_in_return_form, item_code, composition, item_label, return_form_structure);
CREATE INDEX capital_labeled_financial_period_idx ON capital_labeled (financial_period);
CREATE INDEX capital_labeled_financial_year_idx ON capital_labeled (financial_year);
